name: Bug Report
description: Report a bug in the Topsort Analytics SDK
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill in as much detail as possible.

  - type: input
    id: library-version
    attributes:
      label: Library version
      description: Which version of `com.topsort:topsort-kt` are you using?
      placeholder: "e.g. 2.0.0"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android API level
      description: What Android API level are you targeting / running on?
      placeholder: "e.g. API 34 / Android 14"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Call `TopsortAnalytics.setup(...)`
        2. Call `TopsortAnalytics.reportImpression(...)`
        3. Observe crash / incorrect behaviour
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened? Include stack traces if available.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context (code snippets, logs, screenshots) that may help.
